symfony/src/Entity/Video.php
<?php

namespace App\Entity;

use App\Repository\VideoRepository;
use App\Entity\Category;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VideoRepository::class)
 */
class Video
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

	/**
	 * @ORM\ManyToOne(targetEntity="Category")
	 */

	private $category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $youtube_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(int $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getYoutubeId(): ?string
    {
        return $this->youtube_id;
    }

    public function setYoutubeId(string $youtube_id): self
    {
        $this->youtube_id = $youtube_id;

        return $this;
    }
}

symfony/src/Controller/VideoController.php
<?php

namespace App\Controller;

use App\Entity\Video;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class VideoController extends AbstractController
{
    /**
     * @Route("/video", name="video")
     */
    public function showVideos()
    {
    	$videos = $this->getDoctrine()->getRepository(Video::class)->findAllWithCategories();
    	return $this->render('video/show_video.html.twig', [
			'videos' => $videos
        ]);
    }

	/**
	 * @Route("show_video/{youtube_id}", name="show_video")
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
    public function showOneVideo($youtube_id)
	{
		$video = $this->getDoctrine()->getRepository(Video::class)->findBy(['youtube_id' => $youtube_id]);
		return $this->render('video/show_one_video.html.twig', ['video' => $video[0]]);

	}

	/**
	 * @Route("/addvideo", name="addvideo")
	 */
	public function addVideo()
	{
		return $this->render('video/addvideo.html.twig', [

		]);
	}

	/**
	 * @Route("/show_video_by_cat/{category_id}", name="show_video_by_cat", requirements={"category_id"="\d"})
	 */

	public function showByCategory(int $category_id)
	{
		$videos = $this->getDoctrine()->getRepository(Video::class)->findByCategory($category_id);
		return $this->render('video/show_video.html.twig', ['videos' => $videos]);
	}
}

symfony/templates/video/addvideo.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello VideoController!{% endblock %}

{% block main %}
    <h1>Добавит видео</h1>
{% endblock %}

symfony/templates/video/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello VideoController!{% endblock %}

{% block main %}
<h1>Видео</h1>
{% endblock %}

symfony/templates/video/show_one_video.html.twig
{% extends 'base.html.twig' %}

{% block main %}
    <h1>{{ video.title }}</h1>
    <iframe width="1280" height="720" src="https://www.youtube.com/embed/{{ video.youtubeId }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
{% endblock %}

symfony/templates/video/show_video.html.twig
{% extends 'base.html.twig' %}

{% block main %}
    <h1>Показать видео</h1>
    <table>
    <tbody>
    {% for video in videos %}

            <tr>
                <td><h1><a href="{{ path('show_video', {'youtube_id' : video.youtubeId}) }}">{{ video.title }}</a></h1></td>
                <td><h3 style="text-align: center;">{{ video.category.title }}</h3></td>
                <td><iframe width="560" height="315" src="https://www.youtube.com/embed/{{ video.youtubeId }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></td>
            </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock %}